name: diffposetalk
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - numpy=1.23
  - scipy
  - matplotlib
  - scikit-learn
  - numba
  - llvmlite
  - pillow
  - opencv
  - cmake
  - eigen
  - boost
  - bzip2
  - cffi
  - ncurses
  - zlib
  - bzip2
  - ca-certificates
  - openssl
  - pip:
      - torch==2.4.0
      - transformers==4.44.0
      - tqdm==4.66.5
      - trimesh==4.4.3
      - pyrender==0.1.45
      - chumpy==0.70
      - librosa==0.10.2.post1
      - soundfile==0.12.1
      - soxr==0.3.7
      - safetensors==0.4.4
      - huggingface-hub==0.24.5
      - filelock==3.15.4
      - fonttools==4.53.1
      - importlib-metadata==8.2.0
      - importlib-resources==6.4.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - markupsafe==2.1.5
      - mesh==1.0.0a1
      - mpmath==1.3.0
      - msgpack==1.0.8
      - networkx==3.1
      - packaging==24.1
      - platformdirs==4.2.2
      - pooch==1.8.2
      - pyglet==2.0.16
      - pyopengl==3.1.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.2
      - pyzmq==26.1.0
      - regex==2024.7.24
      - requests==2.32.3
      - six==1.16.0
      - threadpoolctl==3.5.0
      - tokenizers==0.19.1
      - typing-extensions==4.12.2
      - urllib3==2.2.2
      - wheel==0.43.0
      - zipp==3.19.2
